/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import java.util.ArrayList;
import static org.junit.Assert.*;

public class ArrayShiftTest {
    @Test public void testInsertShiftArray() {
        int[] array = {1,2,3,5};
        int[] array2 = {2,4,6,8,10};
        int[] array3 = new int[0];

        int[] arrayExpect = {1,2,6,3,5};
        int[] array2Expect = {2,4,6,7,8,10};
        int[] array3Expect = {7};

        assertArrayEquals(arrayExpect, ArrayShift.insertShiftArray(array, 6));
        assertArrayEquals(array2Expect, ArrayShift.insertShiftArray(array2, 7));
        assertArrayEquals(array3Expect, ArrayShift.insertShiftArray(array3, 7));
    }
}
